updated workflows to deploy to Dev env

diff --git a/.github/workflows/solar-system.yml b/.github/workflows/solar-system.yml
--- a/.github/workflows/solar-system.yml
+++ b/.github/workflows/solar-system.yml
@@ -268,13 +268,13 @@ jobs:
         CI_ROLE: ${{ secrets.CI_ROLE }} 
         mongodb-password: ${{ secrets.MONGO_PASSWORD}}
 
-    output-url:
-      runs-on: ubuntu-latest
-      needs: dev-deploy
-      steps:
-      - name: Output ALB Host URL
-        run: |
-         echo "The application URL is: ${{ needs.dev-deploy.outputs.alb_host_url }}"
+    # output-url:
+    #   runs-on: ubuntu-latest
+    #   needs: dev-deploy
+    #   steps:
+    #   - name: Output ALB Host URL
+    #     run: |
+    #      echo "The application URL is: ${{ needs.dev-deploy.outputs.alb_host_url }}"
 
   
     dev-integration-testing:
@@ -284,13 +284,23 @@ jobs:
         runs-on: ubuntu-latest
 
         steps:
-        - name: Run integration tests
+        - name: Test `/live` Endpoint
           env:
-            URL: ${{ needs.dev-deploy.outputs.alb_host_url }}
-
+            INGRESS_HOST: solar-system-dev.dominicsheytanya.org  
           run: |
-            echo "Testing $URL"
-            curl -s -k https://$URL/live | jq -r '.status' | grep -qi live
+             echo "Testing endpoint: http://$INGRESS_HOST/live"
+
+              for i in {1..10}; do
+                if curl -sf http://$INGRESS_HOST/live; then
+                  echo "Live endpoint is healthy"
+                  exit 0
+                fi
+                echo " Waiting for /live endpoint..."
+                sleep 10
+              done
+        
+              echo "Failed to reach /live endpoint at http://$INGRESS_HOST/live"
+              exit 1
 
 
     prod-deploy:
