updated workflow and delpoy to dev

diff --git a/.github/workflows/solar-system.yml b/.github/workflows/solar-system.yml
--- a/.github/workflows/solar-system.yml
+++ b/.github/workflows/solar-system.yml
@@ -271,29 +271,30 @@ jobs:
   
 
 
-    dev-integration-testing:
-        if: contains(github.ref, 'feature/')
-        name: Dev Integration Testing
-        needs: dev-deploy
-        runs-on: ubuntu-latest
-        steps:
-           - name: Test `/live` Endpoint
-             env:
-               INGRESS_HOST: solar-system-dev.dominicsheytanya.org  
-             run: |
-                 echo "Testing endpoint: http://$INGRESS_HOST/live"
+    # dev-integration-testing:
+    #     if: contains(github.ref, 'feature/')
+    #     name: Dev Integration Testing
+    #     needs: dev-deploy
+    #     runs-on: ubuntu-latest
+    #     steps:
+    #        - name: Test `/live` Endpoint
+    #          env:
+    #            INGRESS_HOST: solar-system-dev.dominicsheytanya.org  
+    #          run: |
+    #              echo "Testing endpoint: http://$INGRESS_HOST/live"
 
-                  for i in {1..10}; do
-                    if curl -sf http://$INGRESS_HOST/live; then
-                      echo "Live endpoint is healthy"
-                      exit 0
-                   fi
-                    echo " Waiting for /live endpoint..."
-                    sleep 10
-                  done
+    #               for i in {1..10}; do
+    #                 if curl -sf http://$INGRESS_HOST/live; then
+    #                   echo "Live endpoint is healthy"
+    #                   exit 0
+    #                fi
+    #                 echo " Waiting for /live endpoint..."
+    #                 sleep 10
+    #               done
         
-                  echo "Failed to reach /live endpoint at http://$INGRESS_HOST/live"
-                  exit 1
+    #               echo "Failed to reach /live endpoint at http://$INGRESS_HOST/live"
+    #               exit 1
+
           # - name: Test URL Output using CURL and JQ
           #   env:
           #      URL: https://${{ steps.fetch-alb-host.outputs.ALB_HOST }}
