Deployment to Dev envronment

diff --git a/.github/workflows/solar-system.yml b/.github/workflows/solar-system.yml
--- a/.github/workflows/solar-system.yml
+++ b/.github/workflows/solar-system.yml
@@ -277,14 +277,31 @@ jobs:
         needs: dev-deploy
         runs-on: ubuntu-latest
         steps:
-          - name: Test URL Output using CURL and JQ
-            env:
-               URL: https://${{ steps.fetch-alb-host.outputs.ALB_HOST }}
-              #  URL: ${{ needs.dev-deploy.outputs.application-url }}
-            run: |
-              echo $URL
-              echo "--------------------------------------------"
-              curl https://$URL/live -s -k | jq -r .status | grep -i live
+           - name: Test `/live` Endpoint
+             env:
+               INGRESS_HOST: solar-system-dev.dominicsheytanya.org  
+             run: |
+                 echo "Testing endpoint: http://$INGRESS_HOST/live"
+
+                  for i in {1..10}; do
+                    if curl -sf http://$INGRESS_HOST/live; then
+                      echo "Live endpoint is healthy"
+                      exit 0
+                   fi
+                    echo " Waiting for /live endpoint..."
+                    sleep 10
+                  done
+        
+                  echo "Failed to reach /live endpoint at http://$INGRESS_HOST/live"
+                  exit 1
+          # - name: Test URL Output using CURL and JQ
+          #   env:
+          #      URL: https://${{ steps.fetch-alb-host.outputs.ALB_HOST }}
+          #     #  URL: ${{ needs.dev-deploy.outputs.application-url }}
+          #   run: |
+          #     echo $URL
+          #     echo "--------------------------------------------"
+          #     curl https://$URL/live -s -k | jq -r .status | grep -i live
 
     prod-deploy:
       if: github.ref == 'refs/heads/main'
@@ -304,13 +321,23 @@ jobs:
         needs: prod-deploy
         runs-on: ubuntu-latest
         steps:
-          - name: Test URL Output using CURL and JQ
-            env:
-              URL: ${{ needs.prod-deploy.outputs.application-url }}
-            run: |
-              echo $URL
-              echo "--------------------------------------------"
-              curl https://$URL/live -s -k | jq -r .status | grep -i live
+           - name: Test `/live` Endpoint
+             env:
+               INGRESS_HOST: solar-system-dev.dominicsheytanya.org  
+             run: |
+                 echo "Testing endpoint: http://$INGRESS_HOST/live"
+
+                  for i in {1..10}; do
+                    if curl -sf http://$INGRESS_HOST/live; then
+                      echo "Live endpoint is healthy"
+                      exit 0
+                   fi
+                    echo " Waiting for /live endpoint..."
+                    sleep 10
+                  done
+        
+                  echo "Failed to reach /live endpoint at http://$INGRESS_HOST/live"
+                  exit 1
 
     # slack-notification:
     #   if: always()
